services:
  - type: web
    name: virtual-id-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: SENDGRID_API_KEY
      - key: GOOGLE_WALLET_ISSUER_ID
      - key: GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL
      - key: GOOGLE_WALLET_SERVICE_ACCOUNT
      - key: PORT
        value: 5002
      - key: NODE_ENV
        value: production
    healthCheckPath: /test-wallet
    autoDeploy: true

  - type: web
    name: virtual-id-frontend
    env: node
    buildCommand: cd Code-a-Thon && npm install && npm run build
    startCommand: cd Code-a-Thon && npm run start
    envVars:
      - key: VITE_SENDGRID_API_KEY
      - key: VITE_SENDGRID_FROM_EMAIL
      - key: VITE_API_URL
    healthCheckPath: /
    autoDeploy: true
